# Generated by Django 3.1.12 on 2022-10-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=256)),
            ],
        ),
    ]
