# Generated by Django 3.1.12 on 2022-10-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='tag_name',
        ),
    ]
