# Generated by Django 3.1.12 on 2022-11-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20221018_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
    ]
