# Generated by Django 3.2 on 2022-11-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
