# Generated by Django 3.1.12 on 2022-11-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20221018_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
    ]
