# Generated by Django 3.2 on 2022-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20221101_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
