# Generated by Django 3.1.12 on 2022-11-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20221018_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
