# Generated by Django 3.2 on 2022-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_tag_description'),
        ('restaurant', '0005_auto_20221103_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
    ]
