# Generated by Django 3.2 on 2022-11-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
