# Generated by Django 3.2 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurant_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
