# Generated by Django 3.2 on 2022-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('restaurant', '0011_alter_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='areas',
            field=models.ManyToManyField(blank=True, to='area.Area'),
        ),
    ]
