# Generated by Django 3.1.12 on 2022-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20221018_0957'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchiuser',
            name='favourite',
        ),
        migrations.AddField(
            model_name='anchiuser',
            name='blacklist_food',
            field=models.ManyToManyField(blank=True, related_name='blacklist_food', to='food.Food'),
        ),
        migrations.AddField(
            model_name='anchiuser',
            name='favourite_food',
            field=models.ManyToManyField(blank=True, related_name='favourite_food', to='food.Food'),
        ),
    ]
