# Generated by Django 3.1.12 on 2022-10-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20221018_0957'),
        ('user', '0002_auto_20221023_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchiuser',
            name='blacklist_restaurant',
            field=models.ManyToManyField(blank=True, related_name='blacklist_restaurant', to='restaurant.Restaurant'),
        ),
        migrations.AddField(
            model_name='anchiuser',
            name='favourite_restaurant',
            field=models.ManyToManyField(blank=True, related_name='favourite_restaurant', to='restaurant.Restaurant'),
        ),
    ]
