# Generated by Django 3.1.12 on 2022-10-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
        ('food', '0002_food_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.Ingredient'),
        ),
    ]
