# Generated by Django 3.1.12 on 2022-10-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='foodName',
            new_name='food_name',
        ),
    ]
