# Generated by Django 3.2 on 2022-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20221101_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='food',
            name='recipe',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
