# Generated by Django 3.2 on 2022-11-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_food_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='food',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
