# Generated by Django 3.2 on 2022-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('food', '0010_auto_20221107_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='areas',
            field=models.ManyToManyField(blank=True, to='area.Area'),
        ),
    ]
