name: Deploy

on:
  push:
    branches:
      - main
env:
  image_repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tags.outputs.value }}    
    steps:
      - uses: actions/checkout@v3
  
      - name: Login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tags
        id: tags
        run: |
          TAGS=${GITHUB_SHA::8}
          echo $TAGS
          echo "::set-output name=value::$(echo $TAGS)"
        shell: bash

      - name: Check if docker image existed
        id: existed
        run: docker manifest inspect ${{ env.image_repository }}:${{ steps.tags.outputs.value }}
        continue-on-error: true
      
      - name: Set up Docker Buildx
        if: steps.existed.outcome == 'failure'
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        if: steps.existed.outcome == 'failure'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.image_repository }}:${{ steps.tags.outputs.value }}
          cache-from: type=registry,ref=${{ env.image_repository }}:${{ secrets.APP_NAME }}-buildcache
          cache-to: type=registry,ref=${{ env.image_repository }}:${{ secrets.APP_NAME }}-buildcache,mode=max
  deploy:
    needs: build
    name: Trigger pipeline Azure devops
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: alexrster/pipelines@v2
        with:
          azure-devops-project-url: ${{ secrets.AZURE_URL }}
          azure-pipeline-name: ${{ secrets.AZURE_PIPELINE_NAME }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables: '{"TAG": "${{ needs.build.outputs.tag }}", "IMAGE_REPOSITORY" : "${{ env.image_repository }}"}'